version: "3.0"
services:
  php:
    build:
      context: ./build/php
    volumes:
      - ./app:/var/www
      - ./persistent/fileadmin:/var/www/docroot/fileadmin
    environment:
      - TYPO3_CONTEXT=Development
    networks:
      - default

  db:
    image: mariadb:10.2
    volumes:
      - ./persistent/database:/var/lib/mysql
      - ./data/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
      - default

networks:
  default:
