version: "3.0"
services:
  php:
    build:
      context: ./build/php
    volumes:
      - ./docroot:/var/www/html
      - .:/var/www
    ports:
      - 80:80
    links:
      - db:db
      - logbook:logbook
    environment:
      - TYPO3_CONTEXT=Development
  db:
    image: mariadb:10.1
    volumes:
      - db:/var/lib/mysql
      - ./database-dump.sql:/var/data/database-dump.sql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  logbook:
    image: alexandergunkel/logbook
    environment:
      - PORT=8080
    ports:
      - 8080:8080
volumes:
  db: