version: "3.0"
services:
  php:
    build:
      context: ./build/php
    volumes:
      - ./docroot:/var/www/html
      - .:/var/www
    links:
      - db:db
    environment:
      - TYPO3_CONTEXT=Development
    networks:
      - default
  db:
    image: mariadb:10.1
    volumes:
      - db:/var/lib/mysql
      - ./database-dump.sql:/var/data/database-dump.sql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
      - default
volumes:
  db:
networks:
  default:
